# Numpy

### Numpy 
* ndarrays - Data Structure
* ndarray form the foundation of pandas data structure

**What is Vectorized operations?**


So let's understand the numpy ndarray

> It's homogeneous multi dimensional array.



Homogeneous means same type data if we are not passing then it will typecast

In [443]:
x = np.array([1, "surya", 3])
print(type(x))   #type of x is ndarray and as we saw earlier it accepts homogeneous data type.
p=[]
for i in range(0,len(x)):
    p.append(type(x[i]))
print(p)     # we can see data type of element is type casted to str due to one hetrogeneous element

<class 'numpy.ndarray'>
[<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>]


In [444]:
#let's see one more example
r= np.array([False,4.0,4])
print(r)
print(type(r))

[type(r[i]) for i in range(0,len(r))]  # We can see all elements got typecasted to float


[0. 4. 4.]
<class 'numpy.ndarray'>


[numpy.float64, numpy.float64, numpy.float64]

#### How to use numpy library?


In [445]:
import numpy as np

In [446]:
#1-D array
a= np.array([1,2,3])
a

array([1, 2, 3])

In [447]:
#2-D array
b= np.array ([[1,2,3],[3,4,5]])   
b

array([[1, 2, 3],
       [3, 4, 5]])

In [448]:
#How to find dimension
b.ndim

2

In [449]:
#Shape of array
b.shape

(2, 3)

Array Creation
We can create numpy arrays in many ways. here are few examples:

#### Numpy.array

In [450]:
a= np.array([[1,2,3],[3,4,5]])
print(type(a))
a


<class 'numpy.ndarray'>


array([[1, 2, 3],
       [3, 4, 5]])

#### Numpy.arange

In [451]:
ar = np.arange(13)   # it will generate number from 0 and with default step as 1. last number is not inclusive
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [452]:
ar1 = np.arange(0,12)  # start from 0 and goes till 11 with step as 1
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [453]:
ar2= np.arange(1,12,2)  # start from one goes till 11 with step size as 2
ar2

array([ 1,  3,  5,  7,  9, 11])

In [454]:
ar3= np.arange(3,12,3)  # start from 3 goes till 11 with step size as 3
ar3

array([3, 6, 9])

In [455]:
ar4= np.arange(3,12,-1)  # empty list because direction is violating
ar4

array([], dtype=int64)

In [456]:
ar5= np.arange(12,3,-1)  # empty list because direction is violating
ar5

array([12, 11, 10,  9,  8,  7,  6,  5,  4])

In [457]:
ar5= np.arange(12,3,1)  # empty list because direction is violating
ar5

array([], dtype=int64)

In [458]:
ar5= np.arange(-12,-3,1)  # empty list because direction is violating
ar5

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4])

#### numpy.linspace


In [459]:
ar5 = np.linspace(1,10,3)  # generates evenly spaced number
ar5

array([ 1. ,  5.5, 10. ])

#### Other functions

In [460]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [461]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [462]:
np.diag([2,3,4,5,6,7])

array([[2, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 7]])

In [463]:
#Random number generators

In [464]:
np.mean(np.random.rand(3))

0.2769413313408052

In [465]:
np.tile(np.array([[1,2],[6,7]]),(1,2,3,2))

array([[[[1, 2, 1, 2],
         [6, 7, 6, 7],
         [1, 2, 1, 2],
         [6, 7, 6, 7],
         [1, 2, 1, 2],
         [6, 7, 6, 7]],

        [[1, 2, 1, 2],
         [6, 7, 6, 7],
         [1, 2, 1, 2],
         [6, 7, 6, 7],
         [1, 2, 1, 2],
         [6, 7, 6, 7]]]])

## NumPy datatypes

In [466]:
ar=np.array([2,-1,6,3],dtype='float')
ar

array([ 2., -1.,  6.,  3.])

In [467]:
b= np.array(ar,dtype='int')
b

array([ 2, -1,  6,  3])

In [468]:
c= np.array(ar,dtype='str')
c

array(['2.0', '-1.0', '6.0', '3.0'], dtype='<U32')

In [469]:
d= np.array(ar,dtype='bool')
d

array([ True,  True,  True,  True])

In [470]:
ar= np.array([1,2,3,4])
ar.dtype

dtype('int64')

In [471]:
ar= np.array([1.,2,3,4])
ar.dtype

dtype('float64')

In [472]:
ar= np.array([True,True,True,False])
ar.dtype

dtype('bool')

In [473]:
ar= np.array(["True","True","True","TestSurya Length"])
ar.dtype

dtype('<U16')

In [474]:
#numpy.ndarray.astype()

In [475]:
ar = np.array([3,-2,8.18])

In [476]:
np.array(ar,dtype='int')

array([ 3, -2,  8])

In [477]:
ar.astype(int)

array([ 3, -2,  8])

In [478]:
# NumPy indexing and slicing

In [479]:
ar=np.arange(7)
ar

array([0, 1, 2, 3, 4, 5, 6])

In [480]:
ar[::-1]


array([6, 5, 4, 3, 2, 1, 0])

In [481]:
ar=np.array([[1,2,3],[2,3,4],[5,6,7],[9,8,7]])
ar[1,2]

4

In [482]:
ar[1,2]=3

In [483]:
ar

array([[1, 2, 3],
       [2, 3, 3],
       [5, 6, 7],
       [9, 8, 7]])

In [484]:
ar[-1]

array([9, 8, 7])

In [485]:
ar[1:,:]

array([[2, 3, 3],
       [5, 6, 7],
       [9, 8, 7]])

In [486]:
# Array slicing
ar

array([[1, 2, 3],
       [2, 3, 3],
       [5, 6, 7],
       [9, 8, 7]])

In [487]:
ar[[0,3,3]]

array([[1, 2, 3],
       [9, 8, 7],
       [9, 8, 7]])

In [488]:
ar[0:,0:3]

array([[1, 2, 3],
       [2, 3, 3],
       [5, 6, 7],
       [9, 8, 7]])

In [489]:
ar[2::2,::2]

array([[5, 7]])

In [490]:
ar=np.array([ 0, 2, 4, 6, 8, 10])

In [491]:
ar[:6]=6

In [492]:
ar

array([6, 6, 6, 6, 6, 6])

In [493]:
ar[1:]=np.ones(5)
ar

array([6, 1, 1, 1, 1, 1])

In [494]:
y=ar%2==0
y

array([ True, False, False, False, False, False])

In [495]:
ar[y]

array([6])

In [496]:
#Array masking

ar=np.array(['Hungary','Nigeria', 'Guatemala','','Poland','','Japan']);

In [497]:
ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'],
      dtype='<U9')

In [498]:
ar[ar=='']="USA"

In [499]:
ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'],
      dtype='<U9')

In [500]:
## Complex indexing

In [501]:
ar=np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [502]:
ar2=np.arange(0,-10,-1)[::-1]
ar2

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [503]:
ar[:10]=ar2

In [504]:
ar

ar3=ar
ar3 = ar.copy()

In [505]:
#Copies and views

np.may_share_memory(ar,ar3)

False

In [506]:
ar3

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0, 10, 11, 12, 13, 14])

In [507]:
ar = np.arange(8)
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [508]:
ar1=ar

In [509]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [510]:
ar1[3]=7    # it will manipulate both the arrays i.e. ar and ar1

In [511]:
np.may_share_memory(ar,ar1)

True

In [512]:
ar1

array([0, 1, 2, 7, 4, 5, 6, 7])

In [513]:
 [ar[i]**3 for i in ar]

[0, 1, 8, 343, 64, 125, 216, 343]

In [514]:
np.logical_and(ar,ar1)

array([False,  True,  True,  True,  True,  True,  True,  True])

In [515]:
np.prod(a,axis=0)

array([ 3,  8, 15])

In [516]:
np.prod(a,axis=1)

array([ 6, 60])

In [517]:
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])

In [518]:
ar.sum(),ar.mean(),np.median(ar),ar.std(),ar.cumsum()

(54, 6.0, 6.0, 2.581988897471611, array([ 2,  5,  9, 14, 20, 27, 35, 44, 54]))

In [519]:
np.all(ar<1)

False

In [520]:
ar

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [521]:
ar.ravel()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [522]:
ar.T.ravel()

array([ 2,  5,  8,  3,  6,  9,  4,  7, 10])